import { Router } from "express";
import { addCustomer, addItem, addLoan, deleteCustomer, deleteItem, deleteLoan, getCustomers, getDetails, getItems, getLoans, getSpecificCustomer, ownerLogin, updateItem, updateLoan } from "../controllers/authController.js";
import { addSale } from "../controllers/salesControllers.js";
import { getGoldPrice } from "../controllers/LivePrice.js";
import { addTransaction, deleteTransaction, editTransaction, getTransactions } from "../controllers/transactions.js";
import { addOrder, deleteOrder, editOrder, getAllNotDeliveredOrders, getOrder, getOrders, updateDeliveryStatus } from "../controllers/orderController.js";
const ownerRouter=Router();
ownerRouter.post("/ownerLogin",ownerLogin);
ownerRouter.post("/getItems",getItems);
ownerRouter.post("/getLoans",getLoans);
ownerRouter.post("/updateItem",updateItem);
ownerRouter.post("/deleteItem",deleteItem);
ownerRouter.post("/addItem",addItem);
ownerRouter.post("/updateLoan",updateLoan);
ownerRouter.post("/deleteLoan",deleteLoan);
ownerRouter.post("/addLoan",addLoan);
ownerRouter.post("/addCustomer",addCustomer);
ownerRouter.post("/deleteCustomer",deleteCustomer);
ownerRouter.post("/getCustomers",getCustomers);
ownerRouter.post("/getSpecificCustomer",getSpecificCustomer);
ownerRouter.post("/addSale",addSale);
ownerRouter.post("/getTransactions",getTransactions);
ownerRouter.post("/addTransaction",addTransaction);
ownerRouter.post("/editTransaction",editTransaction);
ownerRouter.post("/deleteTransaction",deleteTransaction);
ownerRouter.post("/addOrder",addOrder);
ownerRouter.post("/editOrder",editOrder);
ownerRouter.post("/deleteOrder",deleteOrder);
ownerRouter.post("/getOrder",getOrder);
ownerRouter.post("/getOrders",getOrders);
ownerRouter.post("/getDashBoard",getDetails);
ownerRouter.get("/getGoldPrice",getGoldPrice);

ownerRouter.post("/updateStatus",updateDeliveryStatus);
ownerRouter.get("/getAllNotDeliveredOrders",getAllNotDeliveredOrders);

export default ownerRouter;